[tool.kedro]
package_name = "modules"
project_name = "modules"
kedro_init_version = "0.18.14"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/modules -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]

# black formatter
[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
      .eggs
    | .git
    | .hg
    | .mypy_cache
    | .tox
    | venv
    | _build
    | buck-out
    | build
    | dist
  )/
'''

# isort
[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true

# flake8
[tool.flake8]
# exclude = ".env"
# ignore = ["E501", "W503", "E226"]
# E501: Line too long
# W503: Line break occurred before binary operator
# E226: Missing white space around arithmetic operator
